### ISSUE TITLE
Features of Controller Board

### ISSUE THREAD

**Issue by tadtruex** [TadAtThayer/MazeController#3]
This is sort of a tracking list for what might go on the main board...

- [x] Joystick
- [x] Ribbon Cable connector
- [x] Accelerometer
- [ ] LED backpack (maybe on Wiring Harness instead)
- [x] Discrete LEDs
- [ ] Buzzer
- [x] Reset Button
- [x] Probe points for PWM checking

Add tracking issues for each of these (attached to Initial Public Release milestone) if they are included.

**Comment by tadtruex** [comment]
Backpack moved to wiring harness.
Buzzer moved to the "what was I thinking" bucket.
